name: Super-Linter

on: push

jobs:
 super-lint:
   name: lint-code-base
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v3
       with:
        fetch-depth: 0

     - name: Run super-linter
       uses: super-linter/super-linter@v6.3.0

       env:
         DEFAULT_BRANCH: main
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         VALIDATE_CHECKOV: false

         
